name: planitt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  syncfusion_flutter_calendar: ^30.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: 2.4.13
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/static/
    - assets/svgs/

  fonts:
    - family: Noto Sans Arabic
      fonts:
        - asset: assets/fonts/static/NotoSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/NotoSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/static/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/NotoSansArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/NotoSansArabic-Black.ttf
          weight: 900

    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Inter_18pt-Italic.ttf
          weight: 400
        - asset: assets/fonts/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Inter_24pt-Light.ttf
          weight: 300
