name: planitt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  awesome_snackbar_content: ^0.1.8
  circular_countdown_timer: ^0.2.4
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  flutter_timezone: ^4.1.1
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  ionicons: ^0.2.2
  lottie: ^3.3.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  syncfusion_flutter_calendar: ^30.2.5
  timezone: ^0.10.1
  translator: ^1.0.4+1
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: 2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  # generate : true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/static/
    - assets/svgs/
    - assets/translation/
    - assets/animations/
    - assets/imgs/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/static/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/static/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/IBMPlexSansArabic-Bold.ttf
          weight: 700

    # - family: Inter
    #   fonts:
    #     - asset: assets/fonts/static/Inter_18pt-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/static/Inter_18pt-Italic.ttf
    #       weight: 400
    #     - asset: assets/fonts/static/Inter_18pt-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/static/Inter_18pt-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/static/Inter_18pt-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/static/Inter_18pt-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/static/Inter_18pt-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/static/Inter_24pt-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/static/Inter_24pt-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/static/Inter_24pt-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/static/Inter_18pt-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/static/Inter_24pt-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/static/Inter_24pt-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/static/Inter_24pt-Light.ttf
    #       weight: 300

    # - family: IBM Plex Sans Arabic
    #   fonts:
    #     - asset: assets/fonts/static/IBMPlexSansArabic-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/static/IBMPlexSansArabic-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/static/IBMPlexSansArabic-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/static/IBMPlexSansArabic-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/static/IBMPlexSansArabic-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/static/IBMPlexSansArabic-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/static/IBMPlexSansArabic-Bold.ttf
    #       weight: 800
